import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Currency Converter - Live Exchange Rates | Convert USD, EUR, INR, GBP, AED & More",
  description: "Free online currency converter with live exchange rates. Convert USD, EUR, INR, GBP, AED, JPY, CAD, AUD and 150+ world currencies instantly using our fast and accurate currency calculator.",
  keywords: [
    "currency converter",
    "usd to inr",
    "aed to inr",
    "eur to inr",
    "gbp to inr",
    "money converter",
    "live exchange rates",
    "Currency Converter",
    "Currency Exchange Calculator",
    "Online Currency Converter",
    "Free Currency Converter",
    "Live Currency Converter",
    "Exchange Rate Calculator",
    "Forex Converter",
    "Money Converter",
    "Currency Calculator",
"Foreign Exchange Calculator",
"USD to INR",
"INR to USD",
"EUR to INR",
"INR to EUR",
"GBP to INR",
"INR to GBP",
"AED to INR",
"INR to AED",
"SAR to INR",
"INR to SAR",
"CAD to INR",
"INR to CAD",
"AUD to INR",
"INR to AUD",
"SGD to INR",
"INR to SGD",
"JPY to INR",
"INR to JPY",
"CHF to INR",
"INR to CHF",
"CNY to INR",
"INR to CNY",
"USD Converter",
"Euro Converter",
"British Pound Converter",
"Japanese Yen Converter",
"Chinese Yuan Converter",
"Canadian Dollar Converter",
"Australian Dollar Converter",
"Swiss Franc Converter",
"Singapore Dollar Converter",
"UAE Dirham Converter",
"Saudi Riyal Converter",
"Qatar Riyal Converter",
"Kuwaiti Dinar Converter",
"Bahraini Dinar Converter",
"Omani Rial Converter",
"Convert currency online",
"Real time currency converter",
"Best currency converter",
"Latest exchange rates",
"Today's exchange rate",
"Live forex rates",
"International currency converter",
"Convert money online",
"Currency conversion tool",
"Exchange rate today",
  ],
  alternates: {
    canonical: "https://bytespin.bytecraftstudio.com/currency-converter",
  },
};