import Navbar from "@/components/layout/Navbar";

export default function AboutPage() {
  return (
    <main className="min-h-screen bg-[#0b1020] text-white">
      <Navbar />

      <div className="max-w-5xl mx-auto px-4 py-20 space-y-20">

        {/* About Us */}
        <section>
          <h1 className="text-4xl md:text-5xl font-black mb-8">
            About ByteSpin
          </h1>

          <div className="space-y-6 text-gray-300 leading-8 text-lg">
            <p>
              ByteSpin is a free online spin wheel and random picker platform
              created by Bytecraft Studio.
            </p>

            <p>
              Our mission is to help users make quick, fair, and fun decisions
              using customizable spinning wheels.
            </p>

            <p>
              Whether you are choosing food, selecting giveaway winners,
              assigning tasks, creating classroom activities, or making daily
              decisions, ByteSpin provides an easy and enjoyable solution.
            </p>

            <p>
              ByteSpin is designed to be fast, mobile-friendly, and completely
              free to use.
            </p>
          </div>
        </section>

        {/* Privacy Policy */}
        <section>
          <h2 className="text-3xl md:text-4xl font-bold mb-8">
            Privacy Policy
          </h2>

          <div className="space-y-6 text-gray-300 leading-8">
            <p>
              We respect your privacy and are committed to protecting your
              personal information.
            </p>

            <p>
              ByteSpin may use cookies and analytics tools such as Google
              Analytics to understand website traffic and improve user
              experience.
            </p>

            <p>
              We do not sell, rent, or share your personal information with
              third parties.
            </p>

            <p>
              By using ByteSpin, you agree to this Privacy Policy.
            </p>
          </div>
        </section>

        {/* Terms of Service */}
        <section>
          <h2 className="text-3xl md:text-4xl font-bold mb-8">
            Terms of Service
          </h2>

          <div className="space-y-6 text-gray-300 leading-8">
            <p>
              ByteSpin is provided for entertainment, productivity, and
              decision-making purposes.
            </p>

            <p>
              Results generated by the spin wheel are random and should not be
              considered legally binding.
            </p>

            <p>
              Users are responsible for how they use the outcomes generated by
              the platform.
            </p>

            <p>
              We reserve the right to modify, update, or discontinue features
              at any time without notice.
            </p>
          </div>
        </section>

        {/* Contact Us */}
        <section>
          <h2 className="text-3xl md:text-4xl font-bold mb-8">
            Contact Us
          </h2>

          <div className="space-y-6 text-gray-300 leading-8">
            <p>
              Have feedback, suggestions, or questions? We'd love to hear from
              you.
            </p>

            <p>
              Email: contact@bytecraftstudio.com
            </p>

            <p>
              <a href="https://www.bytecraftstudio.com/">Our Official Website</a>
            </p>
          </div>
        </section>

      </div>
    </main>
  );
}