export default function TermsPage() {
  return (
    <main className="max-w-4xl mx-auto px-6 py-12 text-white">
      <h1 className="text-4xl font-bold mb-6">Terms & Conditions</h1>

      <p className="mb-4">
        ByteSpin is provided for entertainment and productivity purposes.
      </p>

      <p className="mb-4">
        Spin results are generated randomly and should not be considered
        legally binding.
      </p>

      <p className="mb-4">
        Users are responsible for how they use the results generated by the
        platform.
      </p>

      <p>
        We reserve the right to update these terms at any time.
      </p>
    </main>
  );
}