import type { Metadata } from "next";
import Navbar from "@/components/layout/Navbar";

export const metadata: Metadata = {
  title: "Terms of Service - ByteSpin",
  description:
    "Review the Terms of Service for ByteSpin. Understand our straightforward usage conditions for our free online randomizers and decision-making tools.",
  alternates: {
    canonical: "https://bytespin.bytecraftstudio.com/terms",
  },
};

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-[#0b1020] text-white">
      <Navbar />

      <section className="max-w-3xl mx-auto px-6 pt-20 pb-24 text-left space-y-10">
        {/* Header Section */}
        <div className="border-b border-white/10 pb-6 text-center sm:text-left">
          <h1 className="text-4xl sm:text-5xl font-black mb-3">Terms of Service</h1>
          <p className="text-gray-400 text-sm">
            Last Updated: June 2026
          </p>
        </div>

        <p className="text-gray-300 leading-relaxed">
          Welcome to ByteSpin! By accessing our website at bytespin.bytecraftstudio.com, you are agreeing to be bound by these Terms of Service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws.
        </p>

        {/* 1. Use License */}
        <div className="space-y-3">
          <h2 className="text-2xl font-bold text-violet-400">1. Use License</h2>
          <p className="text-gray-300 leading-relaxed text-sm">
            Permission is granted to temporarily utilize the micro-utility web applications on ByteSpin's website for personal, non-commercial transitory viewing and execution only. This is the grant of a license, not a transfer of title, and under this license, you may not:
          </p>
          <ul className="list-disc pl-6 space-y-2 text-sm text-gray-300">
            <li>Modify, scrape, or copy the underlying client-side source code layout framework.</li>
            <li>Use the tools for any commercial automation workflow without explicit operational permission.</li>
            <li>Attempt to decompile or reverse engineer any script asset contained on ByteSpin's website.</li>
            <li>Remove any copyright or other proprietary notations from the source materials.</li>
          </ul>
        </div>

        {/* 2. Disclaimer */}
        <div className="space-y-3">
          <h2 className="text-2xl font-bold text-violet-400">2. Disclaimer</h2>
          <p className="text-gray-300 leading-relaxed text-sm">
            The materials and generated results on ByteSpin's website are provided on an 'as is' basis. ByteSpin makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
          </p>
          <p className="text-gray-300 leading-relaxed text-sm">
            Further, ByteSpin does not warrant or make any representations concerning the mathematical absolute predictability or reliability of the outcomes generated by its client-side randomization engines.
          </p>
        </div>

        {/* 3. Limitations of Liability */}
        <div className="space-y-3">
          <h2 className="text-2xl font-bold text-violet-400">3. Limitations</h2>
          <p className="text-gray-300 leading-relaxed text-sm">
            In no event shall ByteSpin or its parent entity, Bytecraft Studio, be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the randomization tools on ByteSpin, even if an authorized representative has been notified orally or in writing of the possibility of such damage.
          </p>
        </div>

        {/* 4. Accuracy of Materials */}
        <div className="space-y-3">
          <h2 className="text-2xl font-bold text-violet-400">4. Revisions and Errata</h2>
          <p className="text-gray-300 leading-relaxed text-sm">
            The materials appearing on ByteSpin's website could include technical, typographical, or photographic errors. ByteSpin does not guarantee that any of the materials on its website are accurate, complete, or current. ByteSpin may make changes to the materials contained on its website at any time without notice.
          </p>
        </div>

        {/* 5. Links */}
        <div className="space-y-3">
          <h2 className="text-2xl font-bold text-violet-400">5. External Links</h2>
          <p className="text-gray-300 leading-relaxed text-sm">
            ByteSpin has not extensively reviewed all of the external sites linked to its web domain and is not responsible for the structural content of any such linked site. The inclusion of any link does not imply endorsement by ByteSpin. Use of any such linked website is entirely at the user's own risk.
          </p>
        </div>

        {/* 6. Governing Law */}
        <div className="space-y-3">
          <h2 className="text-2xl font-bold text-violet-400">6. Governing Law</h2>
          <p className="text-gray-300 leading-relaxed text-sm">
            These terms and conditions are governed by and construed in accordance with standard internet deployment frameworks and you irrevocably submit to the exclusive jurisdiction of the state or local courts matching our corporate registration base.
          </p>
        </div>
      </section>

      {/* --- TRUST FOOTER --- */}
      <footer className="max-w-4xl mx-auto px-6 pb-16 text-center border-t border-white/10 pt-8">
        <div className="flex flex-wrap justify-center gap-6 text-xs font-semibold text-gray-400">
          <a href="/about" className="hover:text-white transition-colors">About</a>
          <span className="text-white/10">•</span>
          <a href="/privacy" className="hover:text-white transition-colors">Privacy Policy</a>
          <span className="text-white/10">•</span>
          <a href="/terms" className="text-white font-bold transition-colors">Terms</a>
          <span className="text-white/10">•</span>
          <a href="/contact" className="hover:text-white transition-colors">Contact</a>
        </div>
        <p className="mt-4 text-xs text-gray-600">
          © 2026 ByteSpin by Bytecraft Studio. All rights reserved.
        </p>
      </footer>
    </main>
  );
}